SCREEN_WIDTH_RATIO = 0.7
SCREEN_HEIGHT_RATIO = 0.6

IMAGE_CONTAINER_RATIO = 0.5
IMAGE_CONTAINER_X_POS_RATIO = 0.2
IMAGE_CONTAINER_Y_POS_RATIO = 0.5

TEXT_CONTAINER_WIDTH_RATIO = 0.5405 #Equvilant to divide by 1.85
TEXT_CONTAINER_HEIGHT_RATIO = 0.45
TEXT_CONTAINER_X_POS_OFFSET = 20
TEXT_CONTAINER_Y_POS_OFFSET_RATIO = 0.05
TEXT_CONTAINER_BACKGORUNDCOLOR = "rgba(20, 20, 80, 180)"


